### ISSUE TITLE
Exporting and importing a form from 2.0.0 to a version higher, causes error

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2432]
### Product versie / Product version

From 6fbaa8d91dd880ae736beb03b66592f399090482 onwards

### Omschrijf het probleem / Describe the bug

Exporting a form containing a logic rule which makes a step not applicable which has been build on 2.0.0 or earlier and importing it to a version that contains commit 6fbaa8d91dd880ae736beb03b66592f399090482 gives the following error:

maykin-media sentry 321351

```
AttributeError: 'str' object has no attribute 'uuid'
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "openforms/forms/admin/views.py", line 85, in form_valid
    self._import_single_form(import_file)
  File "openforms/forms/admin/views.py", line 108, in _import_single_form
    created_fds = import_form(import_file)
  File "contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "openforms/forms/utils.py", line 137, in import_form
    return import_form_data(import_data, existing_form_instance)
  File "contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "openforms/forms/utils.py", line 225, in import_form_data
    deserialized.is_valid(raise_exception=True)
  File "rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "rest_framework/serializers.py", line 483, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "rest_framework/serializers.py", line 618, in run_validation
    value = self.to_internal_value(data)
  File "rest_framework/serializers.py", line 666, in to_internal_value
    validated = self.child.run_validation(item)
  File "rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "openforms/forms/api/serializers/logic/action_serializers.py", line 151, in validate
    data["form_step_uuid"] = form_step.uuid
```

### Stappen om te reproduceren / Steps to reproduce

On 2.0.0:
- Create a form with a rule that makes a step not applicable
- Export the form
- In a version that contains commit 6fbaa8d91dd880ae736beb03b66592f399090482 import the form
- Observe error

### Verwacht gedrag / Expected behavior

Shouldn't crash

### Screen resolution

None

### Device

None

### OS

None
